import Head from 'next/head';
import Navbar from '@components/Navbar';
import fs from 'fs'
import path from 'path'
import matter from 'gray-matter'
import Image from 'next/image';
import Link from 'next/link';

export async function getStaticProps() {
  const files = fs.readdirSync(path.join('posts'))
  const posts = files.map(filename => {
    const markdownWithMeta = fs.readFileSync(path.join('posts', filename), 'utf-8')
    const { data: frontMatter } = matter(markdownWithMeta)
    return {
      frontMatter,
      slug: filename.split('.')[0]
    }
  })
  return {
    props: {
      posts
    }
  }
}

export default function Posts({ posts }) {
  return (
    <>
      <Head>
        <title>Posts | Next MDX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className="dark:bg-neutral-900 min-h-screen p-4">
        <h1 className="text-center pt-10 text-4xl dark:text-white font-bold">Posts</h1>
        <div className="mx-auto max-w-3xl py-10 grid md:grid-cols-2 gap-6">
          {posts.map((post, index) => (
            <Link href={'/posts/' + post.slug} passHref key={index}>
              <div className="border dark:border-neutral-700 rounded-lg group">
                <div className="m-auto">
                  <Image
                    src={post.frontMatter.thumbnailUrl}
                    className="rounded-lg"
                    alt="thumbnail"
                    width={500}
                    height={400}
                    objectFit="cover"
                  />
                </div>
                <div className="p-4">
                  <h5 className="text-xl font-medium dark:text-white group-hover:text-sky-600 transition-all">{post.frontMatter.title}</h5>
                  <p className="text-neutral-700 dark:text-neutral-200 my-2">{post.frontMatter.description}</p>
                  <p className="text-sm text-neutral-500 dark:text-neutral-400">{post.frontMatter.date}</p>
                </div>
              </div>
            </Link>
          ))}
        </div>
      </main>
    </>
  )
}